name: Nutrition API - CD

on:
  push:
    branches:
      - "main"
      - "release/*"

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
  
    - name: Publish API package to deploy
      run: dotnet publish ./src/Nutrition-Advisor.Api/Nutrition-Advisor.Api.csproj --configuration Release --no-build --output ./publish  

    - name: Replace tokens
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/appsettings.json"]'
      env:
        OpenAi_ApiKey: ${{ secrets.OPENAI_API_KEY }}

    # to-do - make these environment variables
    - name: Login to Azure using managed identity
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'as-nutrition-api-dv-eastus'
        package: ./publish