name: Nutrition API - CD

on:
  push:
    branches:
      - "main"
      - "release/*"

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
    - uses: actions/checkout@v4
  
    - name: Get the latest ci workflow run-id for the deployment artifact
      id: get_run_id
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo;
          const workflow_id = 'ci.yml';
          const runs = await github.actions.listWorkflowRuns({
            owner,
            repo,
            workflow_id,
            per_page: 1
          });
          const latest_run_id = runs.data.workflow_runs[0].id;
          core.setOutput('run_id', latest_run_id);

    - name: Download API package from build pipeline
      uses: actions/download-artifact@v4
      with:
        name: nutrition-api
        path: ./publish
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ steps.get_run_id.outputs.run_id }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'as-nutrition-api-dv-eastus'
        package: ./publish

    - name: Azure App Service Restart
      run: az webapp restart --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}