name: Nutrition API - CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - development
          - production
        default: development
      run_id:
        description: 'CI run id (https://api.github.com/repos/almantask/nutrition-advisor/actions/runs). If not provided will use latest.'
        required: false
        default: ''

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: ${{ inputs.environment }}

    steps:
    - name: Get the latest ci workflow run-id for the deployment artifact
      id: get_run_id
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const providedRunId = "${{ github.event.inputs.run_id }}";
          if (providedRunId) {
            core.setOutput('run_id', providedRunId);
            console.log(`Using provided run_id: ${providedRunId}`);
          } else {
            const workflow_id = 'ci.yml';
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id,
              per_page: 1
            });
            const latest_run_id = runs.data.workflow_runs[0].id;
            core.setOutput('run_id', latest_run_id);
            console.log(`Using latest run_id: ${latest_run_id}`);
          }
          


    - name: Download API package from build pipeline
      uses: actions/download-artifact@v4
      with:
        name: nutrition-api
        path: ./publish
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ steps.get_run_id.outputs.run_id }}

    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/appsettings.json"]'
      env:
        OpenAi_ApiKey: ${{ secrets.OPENAI_API_KEY }}

    # to-do - make these environment variables
    - name: Login to Azure using managed identity
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: as-nutrition-api-${{ vars.ENV_PREFIX }}-eastus
        package: ./publish